//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artist_CC
    {
        public int artist_id { get; set; }
        public string artist_address { get; set; }
        public string artist_image { get; set; }
        public string artist_genre { get; set; }
        public Nullable<System.Guid> artist_userid { get; set; }
    }
}
