//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int cart_id { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<decimal> subtotal { get; set; }
        public Nullable<int> artwork_id { get; set; }
        public int cus_Id { get; set; }
        public Nullable<int> order_id { get; set; }
    
        public virtual Artwork_W Artwork { get; set; }
        public virtual Customer_CC Customer_CC { get; set; }
        public virtual Order Order { get; set; }
    }
}
