//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class WishList
    {
        public int wishlist_Id { get; set; }
        public int artwork_id { get; set; }
        public int cust_id { get; set; }
    
        public virtual Artwork_W Artwork { get; set; }
        public virtual Customer_CC Customer { get; set; }
    }
}
