//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderCart
    {
        public int OrderId { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> artwork_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<decimal> shipment_Price { get; set; }
        public string status { get; set; }
        public Nullable<decimal> unit_price { get; set; }
    
        public virtual Artwork Artwork { get; set; }
    }
}
